version: '3'
services:
  redis:
    image: "redis"
    ports:
      - 6379:6379
  app:
    build: .
    ports:
      - 3000:9000
    depends_on:
      - redis
    links:
      - redis
  app1:
    build: .
    ports:
      - 3001:9000
    links:
      - redis
    depends_on:
      - redis
  nginx:
    container_name: nginx
    image: nginx:1.17.2-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - app1